zh-CN: &zh
    0: "成功"
    10000: "失败"
    20001: "Token缺失"
    20002: "Token已过期"
    20003: "Token错误"
    30001: "用户不存在"
    30002: "密码错误"
    40001: "参数无效"
    40002: "对象不存在"
    40003: "对象已存在"
    50001: "服务器内部错误"
    60001: "任务已完成"
    60002: "任务类型有误"

en-US:
    <<: *zh
    # 英文编码
    0: "success"
    10000: "fail"
    20001: "Token missing"
    20002: "Token expired"
    20003: "Token error"
    30001: "User not found"
    30002: "Password error"
    40001: "Invalid argument"
    40002: "Object not found"
    40003: "Object already existed"
    50001: "Internal server error"
    60001: "Quest finished"
    60002: "Quest type error"